M48
; DRILL file {KiCad 7.0.7} date Mon Nov 20 10:45:33 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-20T10:45:33-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.4385Y-2.5358
X5.4385Y-4.3842
X6.4035Y-2.5358
X6.4035Y-4.3842
T2
X2.923Y-1.66
X5.1124Y-1.66
T0
M30
